FROM python:3.8
LABEL maintainer twtrubiks
ENV PYTHONUNBUFFERED 1
RUN mkdir /django_crawler_celery
WORKDIR /django_crawler_celery
COPY . /django_crawler_celery/
RUN pip install -r requirements.txt



